##                                                                                                              
## Dit bestand is in toml-formaat, zie: https://github.com/mojombo/toml                                         
##                                                                                                              

logfile = "log/alpiner.log"

about = '''
Experimentele server, niet voor productiedoeleinden.

Info: https://github.com/rug-compling/alpino-api
'''

port = 11200

tmp = "/tmp/alpiner"

# werkelijke interval een minuut langer dan de interval gerapporteerd aan gebruiker
interval = 300
interval_system = 360

workers = 10

timeout_default = 60

timeout_max = 600

timeout_values = [ 20, 60, 600 ]

max_jobs = 6

max_tokens = 100

# tekst uit bestand $ALPINO_HOME/version
# gelijk voor tokenizer en parser
alpino_build = "Alpino-x86_64-Linux-glibc-2.19-20973-sicstus"

[[alpino]]
server = "127.0.0.1:11211"
timeout = 20

[[alpino]]
server = "127.0.0.1:11212"
timeout = 60

[[alpino]]
server = "127.0.0.1:11213"
timeout = 600

[[alpino]]
server = "127.0.0.1:11221"
timeout = 20
parser = "qa"

[[alpino]]
server = "127.0.0.1:11222"
timeout = 60
parser = "qa"

[[alpino]]
server = "127.0.0.1:11223"
timeout = 600
parser = "qa"
